version: '3'
services:
  crunch-app:
    container_name: crunch-app
    image: emkay411/crunch
    restart: always
    build: .
    ports:
      - "80:80"
    environment:
      - MONGO_URL=mongodb://mongo:27017/crunch
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"

volumes:
  data:

